// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHyqAEwiCW7qtFyqXSppFtkGmlo8-nAk',
    appId: '1:331169602720:web:1efb0cac75d69e7b77bdc5',
    messagingSenderId: '331169602720',
    projectId: 'lost-found-app-6f218',
    authDomain: 'lost-found-app-6f218.firebaseapp.com',
    storageBucket: 'lost-found-app-6f218.firebasestorage.app',
    measurementId: 'G-07V1WSRFYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeaAfCGYRrYdxdPG1Duc8FCFo6ZTl8nQM',
    appId: '1:331169602720:android:aefdf7759412a0a077bdc5',
    messagingSenderId: '331169602720',
    projectId: 'lost-found-app-6f218',
    storageBucket: 'lost-found-app-6f218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_fBZkMp_u2WgLSsmwxobLmLiDNOw3mIg',
    appId: '1:331169602720:ios:f0305445be442ee177bdc5',
    messagingSenderId: '331169602720',
    projectId: 'lost-found-app-6f218',
    storageBucket: 'lost-found-app-6f218.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fBZkMp_u2WgLSsmwxobLmLiDNOw3mIg',
    appId: '1:331169602720:ios:f0305445be442ee177bdc5',
    messagingSenderId: '331169602720',
    projectId: 'lost-found-app-6f218',
    storageBucket: 'lost-found-app-6f218.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHyqAEwiCW7qtFyqXSppFtkGmlo8-nAk',
    appId: '1:331169602720:web:ebe3bcad6da2a43b77bdc5',
    messagingSenderId: '331169602720',
    projectId: 'lost-found-app-6f218',
    authDomain: 'lost-found-app-6f218.firebaseapp.com',
    storageBucket: 'lost-found-app-6f218.firebasestorage.app',
    measurementId: 'G-D2FQBCSKPV',
  );
}
